# src/config.py

# Diccionario completo extraído del listado BYMA 2026
CEDEAR_MAP = {
    "MMM":   {"name": "3M Company", "ratio": 10},
    "ABT":   {"name": "Abbott Labs", "ratio": 4},
    "ABBV":  {"name": "AbbVie Inc.", "ratio": 10},
    "ACN":   {"name": "Accenture", "ratio": 75},
    "ADGO":  {"name": "Adecoagro S.A", "ratio": 1},
    "ADBE":  {"name": "Adobe Systems", "ratio": 44},
    "AMD":   {"name": "Advanced Micro Devices", "ratio": 10},
    "ABNB":  {"name": "Airbnb inc", "ratio": 15},
    "BABA":  {"name": "Alibaba Group", "ratio": 9},
    "GOOGL": {"name": "Alphabet Inc.", "ratio": 58},
    "AMZN":  {"name": "Amazon.com, Inc.", "ratio": 144},
    "AAPL":  {"name": "Apple Inc.", "ratio": 20},
    "ARKK":  {"name": "ARK Innovation ETF", "ratio": 10},
    "T":     {"name": "AT&T Inc.", "ratio": 3},
    "BA.C":  {"name": "Bank Of America", "ratio": 4},
    "B":     {"name": "Barrick Gold Corp", "ratio": 2},
    "BRKB":  {"name": "Berkshire Hathaway", "ratio": 22},
    "BX":    {"name": "Blackstone Inc.", "ratio": 30},
    "CAT":   {"name": "Caterpillar Inc", "ratio": 20},
    "CVX":   {"name": "Chevron Corp.", "ratio": 16},
    "CSCO":  {"name": "Cisco Systems", "ratio": 5},
    "C":     {"name": "Citigroup Inc", "ratio": 3},
    "KO":    {"name": "The Coca Cola Company", "ratio": 5},
    "COST":  {"name": "Costco Wholesale", "ratio": 48},
    "DISN":  {"name": "The Walt Disney Co.", "ratio": 12},
    "GE":    {"name": "General Electric", "ratio": 8},
    "GLOB":  {"name": "Globant S.A", "ratio": 18},
    "IBM":   {"name": "International Business Machines", "ratio": 15},
    "INTC":  {"name": "Intel Corporation", "ratio": 5},
    "JPM":   {"name": "J.P. Morgan & Chase", "ratio": 15},
    "JNJ":   {"name": "Johnson & Johnson", "ratio": 15},
    "MELI":  {"name": "Mercadolibre Inc.", "ratio": 120},
    "META":  {"name": "Meta Platforms Inc", "ratio": 24},
    "MSFT":  {"name": "Microsoft Corp.", "ratio": 30},
    "NFLX":  {"name": "Netflix, Inc.", "ratio": 48},
    "NVDA":  {"name": "Nvidia Corporation", "ratio": 24},
    "PYPL":  {"name": "Paypal Holdings", "ratio": 8},
    "PBR":   {"name": "Petrobras (ADR)", "ratio": 1},
    "QCOM":  {"name": "Qualcomm Inc.", "ratio": 11},
    "SHOP":  {"name": "Shopify Inc.", "ratio": 107},
    "SPOT":  {"name": "Spotify Technology", "ratio": 28},
    "TSLA":  {"name": "Tesla, Inc.", "ratio": 15},
    "UBER":  {"name": "Uber Technologies Inc.", "ratio": 2},
    "V":     {"name": "Visa Inc", "ratio": 18},
    "VIST":  {"name": "Vista Energy", "ratio": 3},
    "WMT":   {"name": "Walmart Inc.", "ratio": 18},
    # Nota: Puedes seguir agregando el resto de los ~300 activos siguiendo este formato.
}
