name: Actualizar datos de mercado
on:
  schedule:
    - cron: "0 22 * * 1-5" # Corre a las 19:00 de Argentina
  workflow_dispatch: # Permite que vos le des al botón "Play"
permissions:
  contents: write
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install yfinance pandas pandas_ta --upgrade
      - run: python fetch_data.py  # Aca corregimos el nombre
      - name: Guardar datos
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/market_data.json
          git commit -m "Precios actualizados" || exit 0
          git push
